#!/bin/bash

mainMenue='
===============  What are we doing today?  ===================

//=========================================[]================\\
||                Job Type:                || Choice Number: ||
|]=========================================[]================[|
|| AD                                      ||              1 ||
|| Inf (External, Internal)                ||              2 ||
|| Web                                     ||              3 ||
|| Multi-Phases                            ||              4 ||
|| Review (Build, Config, Firewall, Cloud) ||              5 ||
|| Mobile                                  ||              6 ||
|| Red Team                                ||              7 ||
\\=========================================[]================//
'

notesMenue='
//=========================================[]================\\
||             Notes Program:              || Choice Number: ||
|]=========================================[]================[|
|| Cherry Tree                             ||              1 ||
|| Other (Any using .txt extension)        ||              2 ||
\\=========================================[]================//
' 

echo '
                       ,      ,
                      /(.-""-.)\
                  |\  \/      \/  /|
                  | \ / =.  .= \ / |
                  \( \   o\/o   / )/
                   \_,  -/  \- ,_/
                     /   \__/   \
                     \ \__/\__/ /
                   ___\ \|--|/ /___
                 /`    \      /    `\
                /       \..../       \
_________ _______  ______   _       _________ _                       
\__    _/(  ___  )(  ___ \ ( \      \__   __/( (    /|
   )  (  | (   ) || (   ) )| (         ) (   |  \  ( |
   |  |  | |   | || (__/ / | |         | |   |   \ | |
   |  |  | |   | ||  __ (  | |         | |   | (\ \) |
   |  |  | |   | || (  \ \ | |         | |   | | \   |
|\_)  )  | (___) || )___) )| (____/\___) (___| )  \  |
(____/   (_______)|/ \___/ (_______/\_______/|/    )_)                                                    
'

if [  -f ".config"  ]
then 
  echo -e '
              <| Config File Identified |>\n'
else
  echo -e '
Hello there, I dont believe we have met have we?!
Well allow me to introduce myself; i was named after... */creating folder structure/*'
  touch .config
  echo "firstTimeRun 1" > .config
  mkdir {AD,Multi-Phases,Mobile,Red-Team}
  mkdir -p Inf/{Internal,External}
  mkdir -p Review/{Build,Config,Firewall,Cloud}
  mkdir -p Web/{Internal,External}
  echo -e "\nWot notez program you be usin'?"
  echo "$notesMenue"
  read notesChoice
  case $notesChoice in
    1)
        notesProg=".ctb"
        echo "$notesProg" >> .config
        ;;
    2)
        notesProg=".txt"
        echo "$notesProg" >> .config
        ;;
  esac
fi

echo "$mainMenue"
read choice

case $choice in
     1)
          echo "ooooh... AD ~ Singer would be proud!"
          ;;
     2)
          echo "ooooh... Inf! Lets go!"
          ;;
     3)
          echo "ooooh... Web! Lets go!"
          ;;
     4)
          echo "ooooh... Multi-Phases ~ A BIG ONE! Lets go!"
          ;;
     5)
          echo "ooooh... A Review ~ lucky you! kek."
          ;;
     6)
          echo "ooooh... Mobile ~ Veryyy fancyyy! Lets go!"
          ;;
     7)
          echo "ooooh... Red Team ~ Sneaky Sneaky! Lets go!"
          ;;
esac

case $choice in
     1)
          echo -e "\nWhat is the job number?"
          read jobnumber
          mkdir AD/$jobnumber
          mkdir -p AD/$jobnumber/{Tool-Output,Reporting,Attachments}
          touch AD/$jobnumber/Notes"$notesProg"
          ;;
     2)
          echo -e "\nWhat is the job number?"
          read jobnumber
          echo '
========  Internal or External? ========
//==================[]================\\
|| Internal         ||              1 ||
|| External         ||              2 ||
\\==================[]================//
          '
          read infchoice
          
          if [ "$infchoice" == "2" ]
          then
            mkdir Inf/External/$jobnumber
            mkdir -p Inf/External/$jobnumber/{Tool-Output,Reporting,Attachments}
            mkdir -p Inf/External/$jobnumber/Reporting/{Upload,Final}
            mkdir -p Inf/External/$jobnumber/Tool-Output/{Nessus,Nmap,Screenshots}
            touch Inf/External/$jobnumber/Notes"$notesProg"
          else
            mkdir Inf/Internal/$jobnumber
            mkdir -p Inf/Internal/$jobnumber/{Tool-Output,Reporting,Attachments}
            mkdir -p Inf/Internal/$jobnumber/Reporting/{Upload,Final}
            mkdir -p Inf/Internal/$jobnumber/Tool-Output/{Nessus,Nmap,Screenshots}
            touch Inf/Internal/$jobnumber/Notes"$notesProg"
          fi
          ;;
     3)
          echo -e "\nWhat is the job number?"
          read jobnumber
          echo '
========  Internal or External? ========
//==================[]================\\
|| Internal         ||              1 ||
|| External         ||              2 ||
\\==================[]================//
          '
          read webchoice
          
          if [ "$webchoice" == "2" ]
          then
            mkdir Web/External/$jobnumber
            mkdir -p Web/External/$jobnumber/{Tool-Output,Reporting,Attachments}
            mkdir -p Web/External/$jobnumber/Reporting/{Upload,Final}
            mkdir -p Web/External/$jobnumber/Tool-Output/{Nmap,SSL,Burp,Saved-Attachments,Screenshots}
            touch Web/External/$jobnumber/Notes"$notesProg"
          else
            mkdir Web/Internal/$jobnumber
            mkdir -p Web/Internal/$jobnumber/{Tool-Output,Reporting,Attachments}
            mkdir -p Web/Internal/$jobnumber/Reporting/{Upload,Final}
            mkdir -p Web/Internal/$jobnumber/Tool-Output/{Nmap,SSL,Burp,Saved-Attachments,Screenshots}
            touch Web/Internal/$jobnumber/Notes"$notesProg"
          fi
          ;;
     4)
          echo -e "\nWhat is the job number?"
          read jobnumber
          mkdir Multi-Phases/$jobnumber

          echo -e "\nHow many phases?"
          read phasenum

          for ((i=1;i<=phasenum;i++));
          do
            echo -e "\nWhat is the phase?\n"
            echo '
=================  What are we doing today?  ==================

//=========================================[]================\\
||                Job Type:                || Choice Number: ||
|]=========================================[]================[|
|| AD                                      ||              1 ||
|| Inf (External, Internal)                ||              2 ||
|| Web                                     ||              3 ||
|| Review (Build, Config, Firewall, Cloud) ||              4 ||
|| Mobile                                  ||              5 ||
|| Red Team                                ||              6 ||
\\=========================================[]================//
            '
               read phasename
               case $phasename in
        1)
               echo "ooooh... AD ~ Singer would be proud!"
               mkdir Multi-Phases/$jobnumber/AD
               mkdir -p Multi-Phases/$jobnumber/AD/{Tool-Output,Reporting,Attachments}
               mkdir -p Multi-Phases/$jobnumber/Reporting/{Upload,Final}
               touch Multi-Phases/$jobnumber/AD/Notes"$notesProg"
               ;;
        2)
              echo "ooooh... Inf! Lets go!"
              mkdir Multi-Phases/$jobnumber/Inf
              mkdir -p Multi-Phases/$jobnumber/Inf/{Tool-Output,Reporting,Attachments}
              mkdir -p Multi-Phases/$jobnumber/Inf/Tool-Output/{Nessus,Nmap,Screenshots}
              mkdir -p Multi-Phases/$jobnumber/Inf/Reporting/{Upload,Final}
              touch Multi-Phases/$jobnumber/Inf/Notes"$notesProg"
              ;;
        3)
              echo "ooooh... Web! Lets go!"
              mkdir Multi-Phases/$jobnumber/Web
              mkdir -p Multi-Phases/$jobnumber/Web/{Tool-Output,Reporting,Attachments}
              mkdir -p Multi-Phases/$jobnumber/Web/Tool-Output/{Nmap,SSL,Burp,Saved-Attachments,Screenshots}
              mkdir -p Multi-Phases/$jobnumber/Web/Reporting/{Upload,Final}
              touch Multi-Phases/$jobnumber/Web/Notes"$notesProg"
              ;; 
     
        4)
              echo "ooooh... A Review ~ lucky you! kek."
              echo -e "\nWhat type? (Build/Config/Firewall/Cloud)?"
              read reviewtype
              mkdir Multi-Phases/$jobnumber/$reviewtype-Review
              mkdir -p Multi-Phases/$jobnumber/$reviewtype-Review/{Tool-Output,Reporting,Attachments}
              mkdir -p Multi-Phases/$jobnumber/$reviewtype-Review/Reporting/{Upload,Final}
              ;;
        5)
              echo "ooooh... Mobile ~ Veryyy fancyyy! Lets go!"
              mkdir Multi-Phases/$jobnumber/Mobile
              mkdir -p Multi-Phases/$jobnumber/Mobile/{Tool-Output,Reporting,Attachments}
              mkdir -p Multi-Phases/$jobnumber/Mobile/Reporting/{Upload,Final}
              ;;
        6)
              echo "ooooh... Red Team ~ Sneaky Sneaky! Lets go!"
              mkdir Multi-Phases/$jobnumber/Red-Team
              mkdir -p Multi-Phases/$jobnumber/Red-Team/{Tool-Output,Reporting,Attachments}
              mkdir -p Multi-Phases/$jobnumber/Red-Team/Reporting/{Upload,Final}
              ;;
              esac
            done  
        ;;
     5)
          echo -e "\nWhat is the job number?"
          read jobnumber
          echo -e "\nWhich review are you working on?"
          echo '
===========  Which Review? ===========
//==================[]================\\
|| Build            ||              1 ||
|| Configuration    ||              2 ||
|| Firewall         ||              3 ||
|| Cloud            ||              4 ||
\\==================[]================//
          '
          read reviewtype
              case $reviewtype in
        1)
              mkdir Review/Build/$jobnumber
              mkdir -p Review/Build/$jobnumber/{Output-Scripts,Reporting,Attachments}
              mkdir -p Review/Build/$jobnumber/Reporting/{Upload,Final}
              ;;

        2)
              mkdir Review/Configuration/$jobnumber
              mkdir -p Review/Configuration/$jobnumber/{Tool-Output,Reporting,Attachments}
              mkdir -p Review/Configuration/$jobnumber/Reporting/{Upload,Final}
              ;;

        3)
              mkdir Review/Firewall/$jobnumber
              mkdir -p Review/Firewall/$jobnumber/{Output-Rules,Reporting,Attachments}
              mkdir -p Review/Firewall/$jobnumber/Reporting/{Upload,Final}
              ;;

        4)
              mkdir Review/Cloud/$jobnumber
              mkdir -p Review/Cloud/$jobnumber/{Tool-Output,Reporting,Attachments}
              mkdir -p Review/Cloud/$jobnumber/Reporting/{Upload,Final}
              ;;
              esac

          ;;
     6)
          echo -e "\nWhat is the job number?"
          read jobnumber
          mkdir Mobile/$jobnumber
          mkdir -p Mobile/$jobnumber/{Tool-Output,Reporting,Attachments}
          mkdir -p Mobile/$jobnumber/Reporting/{Upload,Final}
          ;;
     7)
          echo -e "\nWhat is the job number?"
          read jobnumber
          mkdir Red-Team/$jobnumber
          mkdir -p Red-Team/$jobnumber/{Tool-Output,Reporting,Attachments}
          mkdir -p Red-Team/$jobnumber/Reporting/{Upload,Final}
          ;;
esac

echo '

========== *snort* Thanks for coming! Comez visitz me anytime! *snort* ==========

~ Created by: Jay Seward. V1.1
'
